services:
  sd-webui:
    image: registry.cn-hangzhou.aliyuncs.com/joybo/stablediffusion-webui:v2025.04.14-action
    container_name: sd-webui
    hostname: sd-webui
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./:/app/stable-diffusion-webui
    ports:
      - "8080:8080"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            # device_ids: ['0']
            capabilities: [gpu]
    stdin_open: true
    tty: true
    restart: no
    networks:
      - ktransformers
    entrypoint: ["ktransformers", "--model_path=/model/DeepSeek-V2-Lite-Chat", "--gguf_path=/model/DeepSeek-V2-Lite-Chat-GGUF", "--port=8080", "--web=True", "--host=0.0.0.0", "--force_think"]

networks:
  ktransformers:
    driver: bridge
    name: ktransformers
