services:
  sd-webui:
    image: registry.cn-hangzhou.aliyuncs.com/joybo/stablediffusion-webui:v2025.04.14-action
    container_name: sd-webui
    hostname: sd-webui
    environment:
      - TZ=Asia/Shanghai
      - HF_ENDPOINT=https://hf-mirror.com
    volumes:
      - E:\ComfyUI\models:/app/stable-diffusion-webui/models
    ports:
      - "7860:7860"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            # device_ids: ['0']
            capabilities: [gpu]
    stdin_open: true
    tty: true
    restart: no
    networks:
      - sd-webui
    command: ./webui.sh --listen --port=7860 --allow-code --api --xformers

networks:
  sd-webui:
    driver: bridge
    name: sd-webui
